### ISSUE TITLE
Can't call macros_info() from .md file mkdocs: Error reading page 'info.md': 'macros_info' is undefined

### ISSUE THREAD

**Issue by MikeLemo1** [fralau/mkdocs-macros-test#1]
Hi I've installed and defined:
```yml
 - macros:
      modules: [mkdocs-macros-test:mkdocs_macros_test]
```

in mkdocs.yml file and when I add the line: `{{ macros_info() }}`  to an empty info.md file I get the following error and mkdocs won't serve the doc:

> ERROR    -  Error reading page 'info.md': 'macros_info' is undefined

Any Idea why does that happen?

Here's the mkdocs.yml file content:
```yml

site_name: My Docs
theme: 
  name: material
  # ---Might be exclusive to Material theme---
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    
    - content.code.copy # Enables  "CODE_BLOCK" Copying
    - content.code.select # Enables "CODE_BLOCK" selection 

    - content.action.edit # ?
    - content.action.view # ?

    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand  
    - navigation.path 

    - toc.integrate # Expands web space over TOC thingy

  language: en

  # ---Might be exclusive to Material theme---
  palette:
    - scheme: slate 
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to light mode    
      primary: teal
      accent: purple    

    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: lime 
# readthedocs


nav:
  - Home: index.md
  - Initial installation: SoftwareDoc.md
  - Tutorial:
    - VSCode_doc.md
  - MkDocs Doc: MkDocs_docs.md
  - Notebook page: jupyer_sandbox.ipynb
  

  - Programming: Programming_Doc.md

  - info.md
  # - Python file: python_script.py




plugins:

  - search
  - table-reader
  - external-markdown
  - autorefs
  - macros:
      modules: [mkdocs-macros-test:mkdocs_macros_test]
      # modules: 
      #  - my_definitions
      # module_name: definitions
      # include_dir: include
      # on_error_fail: true
      # on_undefined: strict

  # For image editing:
  - glightbox
  - mkdocs-jupyter:
      theme: dark
      ignore: ["./jupyer_sandbox.ipynb", "./Jupiter_journey.ipynb", ACDC_Experinments.ipynb]
      include_requirejs: true


extra_javascript:
#  Enables mathjax latex
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# ---Might be exclusive to Material theme---
markdown_extensions:

  # - external-markdown # Might break some stuff

  - footnotes
  # - toc(permalink=true)
  - toc:
      permalink: "##"

  - mdx_math
  - pymdownx.snippets
  - pymdownx.smartsymbols

  # Embed mathjax equation notations
  - pymdownx.arithmatex

  # sub snd super scripting enabled 
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # Extension to show keyboard shourtcut:
  - pymdownx.keys

  # Used for codeblock design 
  - pymdownx.highlight:
      # Enables line numbering option
      linenums: true
      # Wat?
      anchor_linenums: true
      # Automatically adds a title to codeblock based of setup
      auto_title: true


  - pymdownx.superfences

  # Integrate pdf files into MD
  - pymdownx.pathconverter:
      base_path: './' # default: ''
      relative_path: '' # default ''
      absolute: true # default: false
      tags: 'a script img link object embed'


```
